# Generated by Django 5.1 on 2024-08-10 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recommendation',
            old_name='movie_list',
            new_name='movie',
        ),
    ]
