# Generated by Django 5.1 on 2024-10-08 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_movie_list_recommendation_movie'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmotionPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emotion', models.CharField(max_length=20)),
                ('genre', models.CharField(max_length=20)),
            ],
        ),
    ]
